### ISSUE TITLE
undefined method `chunk_while' for []:Array (NoMethodError)

### ISSUE THREAD

**Issue by meineerde** [asterite/rufo#16]
The following code triggers a bug:

```
require 'uri'

def to_uri(string)
  uri = URI(string)
  uri
end
```

The generated stack trace is:

```
~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:2501:in `do_align': undefined method `chunk_while' for []:Array (NoMethodError)
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:2484:in `do_align_comments'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/formatter.rb:87:in `format'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/command.rb:95:in `format'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/command.rb:16:in `format_stdin'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/lib/rufo/command.rb:8:in `run'
  from ~/.rvm/gems/ruby-2.2.6/gems/rufo-0.0.5/exe/rufo:4:in `<top (required)>'
  from ~/.rvm/gems/ruby-2.2.6/bin/rufo:22:in `load'
  from ~/.rvm/gems/ruby-2.2.6/bin/rufo:22:in `<main>'
  from ~/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `eval'
  from ~/.rvm/gems/ruby-2.2.6/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by meineerde** [comment]
This error goes away when using Ruby 2.4.

It appears `Enumerable#chunk_while` is only available since Ruby 2.3. Which makes this the current minimal Ruby version. Is this intended?

**Comment by asterite** [comment]
I implemented `chunk_while` now if it's not available, for backwards compatibility. Can you check if it works now? I just pushed version 0.0.6

**Comment by meineerde** [comment]
Now, it works on Ruby 2.2 too. Thank you very much!
